module.exports.forex = [
  {
    symbol: "AED/USD",
    currency_group: "Exotic",
    currency_base: "UAE Dirham",
    currency_quote: "US Dollar",
  },
  {
    symbol: "AFN/USD",
    currency_group: "Minor",
    currency_base: "Afghanistan Afghani",
    currency_quote: "US Dollar",
  },
  {
    symbol: "ARS/USD",
    currency_group: "Exotic",
    currency_base: "Argentinian Peso",
    currency_quote: "US Dollar",
  },
  {
    symbol: "AUD/USD",
    currency_group: "Major",
    currency_base: "Australian Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "BOB/USD",
    currency_group: "Exotic",
    currency_base: "Bolivian Boliviano",
    currency_quote: "US Dollar",
  },
  {
    symbol: "BRL/USD",
    currency_group: "Exotic",
    currency_base: "Brazil Real",
    currency_quote: "US Dollar",
  },
  {
    symbol: "BYN/USD",
    currency_group: "Minor",
    currency_base: "Belarusian Ruble",
    currency_quote: "US Dollar",
  },
  {
    symbol: "CAD/USD",
    currency_group: "Major",
    currency_base: "Canadian Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "CHF/USD",
    currency_group: "Major",
    currency_base: "Swiss Franc",
    currency_quote: "US Dollar",
  },
  {
    symbol: "CLP/USD",
    currency_group: "Exotic",
    currency_base: "Chilean Peso",
    currency_quote: "US Dollar",
  },
  {
    symbol: "CNY/USD",
    currency_group: "Exotic",
    currency_base: "Chinese Yuan",
    currency_quote: "US Dollar",
  },
  {
    symbol: "COP/USD",
    currency_group: "Exotic",
    currency_base: "Colombian Peso",
    currency_quote: "US Dollar",
  },
  {
    symbol: "CZK/USD",
    currency_group: "Minor",
    currency_base: "Czech Koruna",
    currency_quote: "US Dollar",
  },
  {
    symbol: "DKK/USD",
    currency_group: "Exotic",
    currency_base: "Danish Krone",
    currency_quote: "US Dollar",
  },
  {
    symbol: "EGP/USD",
    currency_group: "Exotic",
    currency_base: "Egyptian Pound",
    currency_quote: "US Dollar",
  },
  {
    symbol: "EUR/USD",
    currency_group: "Major",
    currency_base: "Euro",
    currency_quote: "US Dollar",
  },
  {
    symbol: "FJD/USD",
    currency_group: "Exotic",
    currency_base: "Fiji Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "GAU/USD",
    currency_group: "Exotic",
    currency_base: "Gold Gram",
    currency_quote: "US Dollar",
  },
  {
    symbol: "GBP/USD",
    currency_group: "Major",
    currency_base: "British Pound",
    currency_quote: "US Dollar",
  },
  {
    symbol: "GHS/USD",
    currency_group: "Exotic",
    currency_base: "Ghanaian Cedi",
    currency_quote: "US Dollar",
  },
  {
    symbol: "HKD/USD",
    currency_group: "Exotic",
    currency_base: "Hong Kong Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "HUF/USD",
    currency_group: "Minor",
    currency_base: "Hungarian Forint",
    currency_quote: "US Dollar",
  },
  {
    symbol: "IDR/USD",
    currency_group: "Minor",
    currency_base: "Indonesian Rupiah",
    currency_quote: "US Dollar",
  },
  {
    symbol: "ILS/USD",
    currency_group: "Exotic",
    currency_base: "Israeli Shekel",
    currency_quote: "US Dollar",
  },
  {
    symbol: "INR/USD",
    currency_group: "Exotic",
    currency_base: "Indian Rupee",
    currency_quote: "US Dollar",
  },
  {
    symbol: "IQD/USD",
    currency_group: "Minor",
    currency_base: "Iraqi Dinar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "IRR/USD",
    currency_group: "Minor",
    currency_base: "Iranian Rial",
    currency_quote: "US Dollar",
  },
  {
    symbol: "JOD/USD",
    currency_group: "Minor",
    currency_base: "Jordan Dinar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "JPY/USD",
    currency_group: "Major",
    currency_base: "Japanese Yen",
    currency_quote: "US Dollar",
  },
  {
    symbol: "KRW/USD",
    currency_group: "Exotic",
    currency_base: "Korean Won",
    currency_quote: "US Dollar",
  },
  {
    symbol: "KWD/USD",
    currency_group: "Minor",
    currency_base: "Kuwaiti Dinar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "KYD/USD",
    currency_group: "Exotic",
    currency_base: "Cayman Islands Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "MXN/USD",
    currency_group: "Exotic",
    currency_base: "Mexican Peso",
    currency_quote: "US Dollar",
  },
  {
    symbol: "MYR/USD",
    currency_group: "Minor",
    currency_base: "Malaysian Ringgit",
    currency_quote: "US Dollar",
  },
  {
    symbol: "NIO/USD",
    currency_group: "Exotic",
    currency_base: "Nicaraguan Cordoba",
    currency_quote: "US Dollar",
  },
  {
    symbol: "NOK/USD",
    currency_group: "Exotic",
    currency_base: "Norwegian Krone",
    currency_quote: "US Dollar",
  },
  {
    symbol: "NZD/USD",
    currency_group: "Major",
    currency_base: "New Zealand Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "PEN/USD",
    currency_group: "Exotic",
    currency_base: "Peru Sol",
    currency_quote: "US Dollar",
  },
  {
    symbol: "PHP/USD",
    currency_group: "Minor",
    currency_base: "Philippine Peso",
    currency_quote: "US Dollar",
  },
  {
    symbol: "PLN/USD",
    currency_group: "Exotic",
    currency_base: "Polish Zloty",
    currency_quote: "US Dollar",
  },
  {
    symbol: "PYG/USD",
    currency_group: "Exotic",
    currency_base: "Paraguayan Guarani",
    currency_quote: "US Dollar",
  },
  {
    symbol: "RUB/USD",
    currency_group: "Exotic",
    currency_base: "Russian Ruble",
    currency_quote: "US Dollar",
  },
  {
    symbol: "SAR/USD",
    currency_group: "Exotic",
    currency_base: "Saudi Riyal",
    currency_quote: "US Dollar",
  },
  {
    symbol: "SEK/USD",
    currency_group: "Exotic",
    currency_base: "Swedish Krona",
    currency_quote: "US Dollar",
  },
  {
    symbol: "SGD/USD",
    currency_group: "Exotic",
    currency_base: "Singapore Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "SYP/USD",
    currency_group: "Minor",
    currency_base: "Syrian Pound",
    currency_quote: "US Dollar",
  },
  {
    symbol: "THB/USD",
    currency_group: "Minor",
    currency_base: "Thai Baht",
    currency_quote: "US Dollar",
  },
  {
    symbol: "TRY/USD",
    currency_group: "Exotic",
    currency_base: "Turkish Lira",
    currency_quote: "US Dollar",
  },
  {
    symbol: "TWD/USD",
    currency_group: "Exotic",
    currency_base: "Taiwan Dollar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "UAH/USD",
    currency_group: "Minor",
    currency_base: "Ukrainian Hryvnia",
    currency_quote: "US Dollar",
  },
  {
    symbol: "URALS/USD",
    currency_group: "Minor",
    currency_base: "Urals Crude Oil Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "UYU/USD",
    currency_group: "Exotic",
    currency_base: "Uruguayan Peso",
    currency_quote: "US Dollar",
  },
  {
    symbol: "VEF/USD",
    currency_group: "Exotic",
    currency_base: "Venezuelan Bolivar",
    currency_quote: "US Dollar",
  },
  {
    symbol: "VND/USD",
    currency_group: "Minor",
    currency_base: "Vietnamese Dong",
    currency_quote: "US Dollar",
  },
  {
    symbol: "WTI/USD",
    currency_group: "Minor",
    currency_base: "Crude Oil WTI Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XAGg/USD",
    currency_group: "Minor",
    currency_base: "Gram Silver",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XAG/USD",
    currency_group: "Exotic",
    currency_base: "Silver Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XAU/USD",
    currency_group: "Exotic",
    currency_base: "Gold Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XBR/USD",
    currency_group: "Minor",
    currency_base: "Brent Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XG/USD",
    currency_group: "Minor",
    currency_base: "Copper Pound",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XPD/USD",
    currency_group: "Minor",
    currency_base: "Palladium Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "XPT/USD",
    currency_group: "Minor",
    currency_base: "Platinum Spot",
    currency_quote: "US Dollar",
  },
  {
    symbol: "ZAR/USD",
    currency_group: "Exotic",
    currency_base: "South African Rand",
    currency_quote: "US Dollar",
  },
];
